name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Maven 3.9.6
      run: |
        sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn clean package
      
    - name: Download opentelemetry-javaagent.jar
      run: |
        mkdir -p example/target
        curl -L -o example/target/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.0/opentelemetry-javaagent.jar

    - name: Build Docker image
      run: docker build example -t example:temp

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push example:temp

    # Add steps for deploying your application
